# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:15
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksDiscoveryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(blank=True, default='', max_length=100)),
                ('authorization_endpoint', models.CharField(blank=True, default='', max_length=100)),
                ('token_endpoint', models.CharField(blank=True, default='', max_length=100)),
                ('userinfo_endpoint', models.CharField(blank=True, default='', max_length=100)),
                ('revocation_endpoint', models.CharField(blank=True, default='', max_length=100)),
                ('jwks_uri', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'QuickBooks Discovery Document',
            },
        ),
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_realm_id', models.IntegerField(null=True)),
                ('quickbooks_access_token', models.CharField(blank=True, default='', max_length=1000)),
                ('quickbooks_access_token_expires_in', models.PositiveIntegerField(null=True)),
                ('quickbooks_refresh_token', models.CharField(blank=True, default='', max_length=100)),
                ('quickbooks_refresh_token_expires_in', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'QuickBooks Token',
            },
        ),
    ]
